"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowUpLeftIcon, CreditCardIcon, KeyRoundIcon, SearchIcon } from "lucide-react";
import { EmptyState } from "@/components/shared/empty-state";
import { PageHeader } from "@/components/shared/page-header";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import type { StudentSubscription, SubscriptionOffer } from "../types/subscriptions";
import { AccessStatusBadge, SubscriptionStatusBadge, formatDate } from "./subscription-status";

export function SubscriptionsPage({ subscriptions, offers }: { subscriptions: StudentSubscription[]; offers: SubscriptionOffer[] }) {
 const [query, setQuery] = useState(""); const [status, setStatus] = useState<"all" | "active" | "expiring_soon" | "expired" | "pending_payment_review">("all");
 const visible = useMemo(() => subscriptions.filter((item) => (status === "all" || item.status === status) && [item.courseTitle,item.subject,item.teacherName,item.groupName].join(" ").includes(query.trim())), [subscriptions,status,query]);
 const counts = { active: subscriptions.filter((x) => x.status === "active").length, renewal: subscriptions.filter((x) => x.status === "expiring_soon").length, pending: subscriptions.filter((x) => x.status === "pending_payment_review").length, expired: subscriptions.filter((x) => x.status === "expired").length };
 return <div className="flex min-w-0 flex-col gap-5 lg:gap-6"><PageHeader title="الاشتراكات" description="تابعي حالة اشتراكات الكورسات، التفعيل، وطلبات المراجعة التجريبية." actions={<Button render={<Link href="/subscriptions/activate" />} nativeButton={false}><KeyRoundIcon data-icon="inline-start" />إدخال كود تفعيل</Button>} />
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["الاشتراكات النشطة",counts.active],["تحتاج تجديد",counts.renewal],["قيد المراجعة",counts.pending],["الاشتراكات المنتهية",counts.expired]].map(([label,value])=><Card key={String(label)} size="sm"><CardContent className="flex items-center justify-between"><span className="text-sm text-muted-foreground">{label}</span><strong className="text-xl text-primary">{value}</strong></CardContent></Card>)}</div>
 <Card><CardContent className="flex flex-col gap-3 sm:flex-row"><div className="relative min-w-0 flex-1"><SearchIcon className="pointer-events-none absolute start-3 top-3 size-4 text-muted-foreground"/><Input aria-label="البحث في الاشتراكات" value={query} onChange={(event)=>setQuery(event.target.value)} className="ps-10" placeholder="ابحثي بالكورس أو المادة أو المدرس" /></div><select aria-label="حالة الاشتراك" className="h-10 rounded-lg border bg-background px-3 text-sm" value={status} onChange={(event)=>setStatus(event.target.value as typeof status)}><option value="all">الكل</option><option value="active">نشط</option><option value="expiring_soon">يحتاج تجديد</option><option value="expired">منتهي</option><option value="pending_payment_review">قيد المراجعة</option></select></CardContent></Card>
 <section className="grid gap-4">{visible.map((item)=><SubscriptionCard key={item.id} item={item}/>)}</section>{subscriptions.length === 0 ? <EmptyState title="لا توجد اشتراكات بعد" description="ستظهر الاشتراكات هنا بعد التفعيل أو إنشاء طلب مراجعة." /> : visible.length === 0 ? <EmptyState title="لا توجد نتائج مطابقة" description="غيّري كلمات البحث أو حالة الاشتراك." /> : null}
 <section className="flex flex-col gap-4"><div><h2 className="text-xl font-semibold">العروض المتاحة</h2><p className="mt-1 text-sm text-muted-foreground">اختاري عرضًا ثم استخدمي كود التفعيل أو اطلبي المراجعة عبر فودافون كاش.</p></div>{offers.length ? <div className="grid gap-4 lg:grid-cols-3">{offers.map((offer)=><Card key={offer.id} className="min-w-0"><CardHeader><div className="flex items-start justify-between gap-2"><div className="min-w-0"><CardTitle>{offer.title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{offer.teacherName} · {offer.groupName}</p></div>{offer.recommended ? <span className="rounded-md bg-primary/10 px-2 py-1 text-xs font-medium text-primary">مقترح</span> : null}</div></CardHeader><CardContent className="flex flex-1 flex-col gap-4"><p className="text-sm leading-6 text-muted-foreground">{offer.description}</p><div className="flex justify-between text-sm"><span>{offer.durationLabel}</span><strong>{offer.price} {offer.currency}</strong></div><ul className="space-y-1 text-xs text-muted-foreground">{offer.features.map((feature)=><li key={feature}>• {feature}</li>)}</ul><div className="mt-auto flex flex-wrap gap-2"><Button size="sm" variant="outline" render={<Link href="/subscriptions/activate" />} nativeButton={false}><KeyRoundIcon data-icon="inline-start"/>استخدام كود</Button><Button size="sm" render={<Link href={`/payments/new?offer=${offer.id}`} />} nativeButton={false} disabled={!offer.available}><CreditCardIcon data-icon="inline-start"/>الدفع عبر فودافون كاش</Button></div></CardContent></Card>)}</div> : <EmptyState title="لا توجد عروض متاحة" />}</section></div>;
}
function SubscriptionCard({ item }: { item: StudentSubscription }) { const primary = item.status === "active" || item.status === "expiring_soon" ? { href: item.status === "active" ? `/courses/${item.courseId}` : "/payments/new", label: item.status === "active" ? "متابعة الكورس" : "تجديد الاشتراك" } : item.status === "pending_payment_review" ? { href: `/payments/${item.latestPaymentId}`, label: "عرض طلب الدفع" } : { href: "/payments/new", label: "تجديد الاشتراك" }; return <Card className="min-w-0"><CardHeader><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 text-start"><p className="text-sm font-medium text-primary">{item.subject}</p><CardTitle className="mt-1 text-xl leading-7">{item.courseTitle}</CardTitle><p className="mt-2 text-sm text-muted-foreground">{item.teacherName} · {item.groupName}</p></div><div className="flex flex-wrap gap-2"><SubscriptionStatusBadge status={item.status}/><AccessStatusBadge status={item.accessStatus}/></div></div></CardHeader><CardContent className="flex flex-col gap-4"><div className="grid gap-2 text-sm text-muted-foreground sm:grid-cols-2 lg:grid-cols-4"><span>البداية: {formatDate(item.startedAt)}</span><span>الانتهاء: {formatDate(item.expiresAt)}</span><span>{item.daysRemaining !== undefined ? `المتبقي: ${item.daysRemaining} يوم` : "المدة حسب العرض"}</span><span>{item.price} {item.currency} · {item.billingType === "monthly" ? "شهري" : item.billingType === "term" ? "ترم" : "كورس"}</span></div><Progress value={item.progress}/><p className="rounded-lg bg-secondary/60 p-3 text-sm leading-6 text-muted-foreground">{item.renewalMessage}</p><div className="flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-muted-foreground">{item.includedFeatures.join(" · ")}</span><Button render={<Link href={primary.href}/>} nativeButton={false}>{primary.label}<ArrowUpLeftIcon data-icon="inline-end"/></Button></div></CardContent></Card>; }
