"use client";

/* The attempt intentionally transitions only from browser timer and monitoring effects. */
/* eslint-disable react-hooks/exhaustive-deps, react-hooks/set-state-in-effect */

import Link from "next/link";
import { useEffect, useMemo, useRef, useState, useTransition } from "react";
import { AlertTriangleIcon, CheckCircle2Icon, ChevronLeftIcon, ChevronRightIcon, Clock3Icon, ExpandIcon, FileTextIcon, LockIcon, PlayIcon, ShieldAlertIcon } from "lucide-react";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import type { LearningCourse, OnlineExam, UnifiedStudentResult } from "../types/learning";
import { saveLessonProgress } from "../services/learning-client";
import { toApiError } from "@/lib/api/errors";

const formatDate = (value?: string) => value ? new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium" }).format(new Date(value)) : "وصول دائم";
const packageLabel = { SINGLE_LESSON: "باقة حصة", MONTHLY: "باقة شهر", TERM: "باقة ترم", FINAL_REVISION: "مراجعة نهائية", CUSTOM: "باقة مخصصة" };
const statusLabel = { UPCOMING: "قادم", AVAILABLE: "متاح", IN_PROGRESS: "قيد الحل", SUBMITTED: "تم التسليم", GRADED: "تم الرصد", EXPIRED: "انتهى" };

export function LearningCoursePage({ course }: { course: LearningCourse }) {
  const active = course.accessState === "ACTIVE";
  return <div className="flex flex-col gap-5 lg:gap-6"><section className="rounded-xl border bg-card p-5 sm:p-6"><p className="text-sm font-medium text-primary">{course.subject} · {course.grade}</p><div className="mt-2 flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><h1 className="text-2xl font-semibold sm:text-3xl">{course.title}</h1><p className="mt-2 text-muted-foreground">{course.teacher} · {course.packageTitle}</p></div><Button disabled={!course.nextLessonId || !active} render={course.nextLessonId && active ? <Link href={`/courses/${course.courseId}/lessons/${course.nextLessonId}`} /> : undefined} nativeButton={false}><PlayIcon data-icon="inline-start" />{active ? "متابعة الدرس" : "تجديد الوصول"}</Button></div><div className="mt-5 grid gap-3 text-sm sm:grid-cols-3"><Info label="نوع الباقة" value={packageLabel[course.packageType]} /><Info label="الصلاحية" value={active ? formatDate(course.expiresAt) : "منتهية"} /><Info label="التقدم" value={`${course.progress}% · ${course.completedLessons}/${course.totalLessons} دروس`} /></div><Progress value={course.progress} className="mt-4" /></section>{!active ? <Alert><LockIcon /><AlertTitle>انتهت صلاحية الوصول الإلكتروني</AlertTitle><AlertDescription>يمكنك مشاهدة هيكل الكورس فقط. تسجيلك في السنتر، إن وجد، لا يفتح الدروس المسجلة.</AlertDescription></Alert> : null}<section><h2 className="text-xl font-semibold">محتوى الكورس</h2><p className="mt-1 text-sm text-muted-foreground">اختاري درسًا متاحًا للمتابعة. الدروس غير المنشورة أو غير المشمولة تبقى واضحة دون إتاحة المحتوى.</p><div className="mt-4 grid gap-3">{course.lessons.map((lesson) => { const progress = lesson.id === course.nextLessonId ? "الحالي" : ""; const unavailable = !active || !lesson.published; const href = `/courses/${course.courseId}/lessons/${lesson.id}`; return <Card key={lesson.id}><CardContent className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-primary">{lesson.unitTitle} · {lesson.duration}</p><h3 className="mt-1 font-semibold">{lesson.title}</h3><p className="mt-1 text-sm text-muted-foreground">{unavailable ? (!active ? "الوصول منتهٍ" : "ينشر قريبًا") : progress || "متاح ضمن الباقة"}</p></div><Button size="sm" variant={unavailable ? "outline" : "default"} render={<Link href={href} />} nativeButton={false}>{unavailable ? "عرض الحالة" : "فتح الدرس"}</Button></CardContent></Card>; })}</div></section></div>;
}
export function MyCoursesPage({ courses }: { courses: LearningCourse[] }) { return <div className="flex flex-col gap-5"><div><h1 className="text-2xl font-semibold">كورساتي الإلكترونية</h1><p className="mt-1 text-sm text-muted-foreground">تظهر هنا الباقات المرتبطة بوصول إلكتروني فقط؛ تسجيل السنتر لا يضيف كورسًا إلى هذه القائمة.</p></div>{courses.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{courses.map((course) => <Card key={course.courseId}><CardHeader><p className="text-sm text-primary">{course.subject} · {course.grade}</p><CardTitle className="mt-1">{course.title}</CardTitle><p className="text-sm text-muted-foreground">{course.teacher} · {course.packageTitle}</p></CardHeader><CardContent className="space-y-4"><p className="text-sm">{course.accessState === "ACTIVE" ? `متاح حتى ${formatDate(course.expiresAt)}` : "انتهت صلاحية الباقة"}</p><Progress value={course.progress} /><p className="text-sm text-muted-foreground">{course.completedLessons}/{course.totalLessons} دروس مكتملة</p><Button size="sm" render={<Link href={`/learn/${course.courseId}`} />} nativeButton={false}>{course.accessState === "ACTIVE" ? "فتح الكورس" : "عرض خيارات التجديد"}</Button></CardContent></Card>)}</div> : <Alert><AlertTriangleIcon /><AlertTitle>لا يوجد وصول إلكتروني نشط</AlertTitle><AlertDescription>يمكنك استكشاف الكورسات أو تفعيل كود وصول. تسجيل السنتر وحده لا يفتح الدروس المسجلة.</AlertDescription></Alert>}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-secondary/60 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-medium">{value}</p></div>; }

type LessonData = NonNullable<Awaited<ReturnType<typeof import("../services/learning-service").getLearningLesson>>>;
export function LearningLessonPage({ data }: { data: LessonData }) {
  const [progress, setProgress] = useState(data.progress.progressPercent);
  const [completed, setCompleted] = useState(data.progress.status === "COMPLETED"); const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  const unlocked = data.state === "UNLOCKED" && data.playback;
  const complete=async()=>{setSaving(true);setError("");try{await saveLessonProgress(data.lesson.id,100);setCompleted(true);setProgress(100);}catch(reason){setError(toApiError(reason).message);}finally{setSaving(false);}}; return <div className="flex flex-col gap-5"><Link className="text-sm font-medium text-primary hover:underline" href={`/courses/${data.courseId}`}>العودة إلى الكورس</Link><section className="rounded-xl border bg-card overflow-hidden"><div className="aspect-video bg-foreground">{unlocked ? <iframe className="h-full w-full" title={data.lesson.title} src={`https://www.youtube-nocookie.com/embed/${data.playback.videoId}?playsinline=1&rel=0&modestbranding=1`} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /> : <div className="flex h-full items-center justify-center p-6 text-center text-background"><div><LockIcon className="mx-auto size-10" /><h1 className="mt-4 text-xl font-semibold">{data.state === "NOT_PUBLISHED" ? "الدرس لم يُنشر بعد" : "الدرس غير متاح الآن"}</h1><p className="mt-2 max-w-md text-sm text-background/75">{data.reason}</p></div></div>}</div><CardContent className="p-5"><p className="text-sm text-primary">{data.course.title} · {data.course.teacher}</p><h1 className="mt-2 text-2xl font-semibold">{data.lesson.title}</h1><p className="mt-3 max-w-3xl leading-7 text-muted-foreground">{data.lesson.description}</p>{unlocked ? <div className="mt-5 rounded-lg bg-secondary/60 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-medium">تقدم الدرس</p><p className="mt-1 text-sm text-muted-foreground">يُحفظ تقدم الدرس في حسابك على الخادم.</p></div><Button disabled={saving||completed} onClick={complete}> <CheckCircle2Icon data-icon="inline-start" />{saving?"جارٍ الحفظ…":completed ? "تم إكمال الدرس" : "تحديد كمكتمل"}</Button></div>{error?<p role="alert" className="mt-2 text-sm text-destructive">{error}</p>:null}<Progress value={progress} className="mt-4" /></div> : <Button className="mt-5" render={<Link href={data.action.href} />} nativeButton={false}>{data.action.label}</Button>}<div className="mt-5"><h2 className="font-semibold">المواد المرفقة</h2>{data.lesson.attachmentNames.length ? <ul className="mt-3 grid gap-2 text-sm text-muted-foreground">{data.lesson.attachmentNames.map((attachment) => <li key={attachment} className="flex items-center gap-2"><FileTextIcon className="size-4 text-primary" />{attachment}</li>)}</ul> : <p className="mt-2 text-sm text-muted-foreground">لا توجد مواد مرفقة لهذا الدرس الآن.</p>}</div></CardContent></section><div className="flex flex-wrap justify-between gap-3"><NavLesson lesson={data.previous} courseId={data.courseId} direction="السابق" /><NavLesson lesson={data.next} courseId={data.courseId} direction="التالي" /></div></div>;
}
function NavLesson({ lesson, courseId, direction }: { lesson?: { id: string; title: string }; courseId: string; direction: string }) { return lesson ? <Button variant="outline" render={<Link href={`/courses/${courseId}/lessons/${lesson.id}`} />} nativeButton={false}>{direction === "السابق" ? <ChevronRightIcon data-icon="inline-start" /> : null}{direction}: {lesson.title}{direction === "التالي" ? <ChevronLeftIcon data-icon="inline-end" /> : null}</Button> : <span />; }

export function ExamsListingPage({ exams }: { exams: OnlineExam[] }) { return <div className="flex flex-col gap-5"><div><h1 className="text-2xl font-semibold">الامتحانات والنتائج</h1><p className="mt-1 text-sm text-muted-foreground">تظهر هنا الاختبارات المخصصة لحسابك فقط، وهي مستقلة عن إتاحة الفيديو.</p></div><div className="flex gap-2"><Button variant="outline" render={<Link href="/results" />} nativeButton={false}>عرض النتائج</Button></div><div className="grid gap-4 lg:grid-cols-2">{exams.map((exam) => <Card key={exam.id}><CardHeader><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-primary">{exam.subject} · {exam.teacher}</p><CardTitle className="mt-1">{exam.title}</CardTitle></div><span className="rounded-full bg-secondary px-3 py-1 text-xs">{statusLabel[exam.status]}</span></div></CardHeader><CardContent className="space-y-3 text-sm"><div className="grid grid-cols-2 gap-3 text-muted-foreground"><span>{exam.questions.length} أسئلة</span><span>{exam.maxScore} درجة</span><span>{exam.durationMinutes} دقيقة</span><span>{exam.attemptsUsed}/{exam.attemptsAllowed} محاولات</span></div><p className="text-muted-foreground">متاح من {formatDate(exam.availableFrom)} حتى {formatDate(exam.availableUntil)}</p><Button size="sm" render={<Link href={`/exams/${exam.id}`} />} nativeButton={false}>{exam.status === "AVAILABLE" ? "عرض التعليمات" : "عرض الحالة"}</Button></CardContent></Card>)}</div></div>; }

export function ExamInstructionPage({ exam }: { exam: OnlineExam }) { const canStart = ["AVAILABLE","IN_PROGRESS"].includes(exam.status) && exam.attemptsUsed <= exam.attemptsAllowed; const [confirmed, setConfirmed] = useState(false); return <div className="mx-auto flex max-w-3xl flex-col gap-5"><Link className="text-sm font-medium text-primary hover:underline" href="/exams">العودة إلى الامتحانات</Link><Card><CardHeader><p className="text-sm text-primary">{exam.subject} · {exam.teacher}</p><CardTitle className="mt-1 text-2xl">{exam.title}</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Info label="الأسئلة" value={`${exam.questions.length}`} /><Info label="المدة" value={`${exam.durationMinutes} دقيقة`} /><Info label="المحاولات" value={`${Math.max(0,exam.attemptsAllowed - exam.attemptsUsed)} متبقية`} /></div><Alert><ShieldAlertIcon /><AlertTitle>تنبيه صريح عن المتابعة</AlertTitle><AlertDescription>يتم تسجيل مغادرة صفحة الامتحان أو الخروج من وضع ملء الشاشة في سجل المحاولة على الخادم. هذه المتابعة للتنبيه فقط ولا تمنع استخدام جهاز آخر.</AlertDescription></Alert><ul className="list-disc space-y-2 pe-5 text-sm leading-6 text-muted-foreground"><li>يمكنك الانتقال بين الأسئلة قبل التسليم.</li><li>ينتهي الاختبار ويُسلَّم عند انتهاء الوقت.</li>{exam.requiresFullscreen ? <li>سيُطلب وضع ملء الشاشة بعد بدء المحاولة فقط.</li> : null}<li>قد يؤدي تجاوز حد التنبيهات إلى التسليم تلقائيًا.</li></ul>{canStart ? <><label className="flex items-start gap-3 rounded-lg border p-3 text-sm"><input className="mt-1 size-4" type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />أفهم أن هذه محاولة فعلية وأن الإجابات والتنبيهات ستُحفظ في حسابي.</label><Button disabled={!confirmed} render={<Link href={`/exams/${exam.id}/take`} />} nativeButton={false}>{exam.status==="IN_PROGRESS"?"استكمال المحاولة":"بدء المحاولة"}</Button></> : <Alert><AlertTriangleIcon /><AlertTitle>لا يمكن بدء هذه المحاولة الآن</AlertTitle><AlertDescription>{exam.status === "EXPIRED" ? "انتهت نافذة الاختبار." : "الاختبار غير متاح بعد أو لا توجد محاولات متبقية."}</AlertDescription></Alert>}</CardContent></Card></div>; }

export function ExamAttemptPage({ exam }: { exam: OnlineExam | null }) { const [answers, setAnswers] = useState<Record<string, string[] | boolean | string>>({}); const [seconds, setSeconds] = useState((exam?.durationMinutes ?? 0) * 60); const [violations, setViolations] = useState<string[]>([]); const [submitted, setSubmitted] = useState(false); const [fullscreenRequested, setFullscreenRequested] = useState(false); const lastEvent = useRef<Record<string, number>>({}); const [, startTransition] = useTransition();
  const record = (kind: string) => { if (!exam || submitted) return; const now = Date.now(); if (now - (lastEvent.current[kind] ?? 0) < 1500) return; lastEvent.current[kind] = now; setViolations((value) => value.includes(kind) ? value : [...value, kind]); };
  useEffect(() => { if (!exam || submitted) return; const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); const hidden = () => document.hidden && record("PAGE_HIDDEN"); const blur = () => record("WINDOW_BLUR"); const full = () => fullscreenRequested && !document.fullscreenElement && record("FULLSCREEN_EXIT"); const copy = () => record("COPY_ATTEMPT"); const paste = () => record("PASTE_ATTEMPT"); const context = () => record("CONTEXT_MENU_ATTEMPT"); document.addEventListener("visibilitychange", hidden); window.addEventListener("blur", blur); document.addEventListener("fullscreenchange", full); window.addEventListener("copy", copy); window.addEventListener("paste", paste); window.addEventListener("contextmenu", context); return () => { window.clearInterval(timer); document.removeEventListener("visibilitychange", hidden); window.removeEventListener("blur", blur); document.removeEventListener("fullscreenchange", full); window.removeEventListener("copy", copy); window.removeEventListener("paste", paste); window.removeEventListener("contextmenu", context); }; }, [exam, submitted, fullscreenRequested]);
  useEffect(() => { if (seconds === 0 && !submitted) setSubmitted(true); }, [seconds, submitted]); useEffect(() => { if (exam && exam.maxViolations > 0 && violations.length >= exam.maxViolations && !submitted) setSubmitted(true); }, [exam, violations.length, submitted]);
  if (!exam || exam.status !== "AVAILABLE") return <div className="mx-auto max-w-xl"><Alert><AlertTriangleIcon /><AlertTitle>المحاولة غير متاحة</AlertTitle><AlertDescription>راجعي حالة الاختبار أو عدد المحاولات المتبقية.</AlertDescription></Alert></div>;
  const objectiveScore = exam.questions.reduce((total, question) => { const answer = answers[question.id]; if (question.type === "SHORT_TEXT") return total; if (question.type === "TRUE_FALSE") return total + (answer === question.correctBoolean ? question.maxScore : 0); const given = Array.isArray(answer) ? answer.sort().join(",") : ""; return total + (given === (question.correctOptionIds ?? []).sort().join(",") ? question.maxScore : 0); }, 0); const manual = exam.questions.some((question) => question.type === "SHORT_TEXT" && answers[question.id]);
  const time = `${String(Math.floor(seconds / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
  if (submitted) return <div className="mx-auto max-w-2xl"><Card><CardHeader><CardTitle>تم تسليم المحاولة التجريبية</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-muted-foreground">{seconds === 0 ? "انتهى الوقت وتم التسليم تلقائيًا." : violations.length >= exam.maxViolations && exam.maxViolations > 0 ? "تم التسليم بعد الوصول إلى حد التنبيهات المحدد." : "تم تسجيل تسليمك."}</p><div className="grid gap-3 sm:grid-cols-3"><Info label="الدرجة الموضوعية" value={`${objectiveScore}/${exam.maxScore}`} /><Info label="التنبيهات" value={`${violations.length}`} /><Info label="المراجعة" value={manual ? "بانتظار مراجعة النص" : "مكتملة"} /></div><Button render={<Link href="/results" />} nativeButton={false}>العودة إلى النتائج</Button></CardContent></Card></div>;
  return <div className="mx-auto flex max-w-5xl flex-col gap-4"><header className="sticky top-0 z-10 rounded-lg border bg-card/95 p-4 backdrop-blur"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-primary">{exam.title}</p><p className="text-sm text-muted-foreground">التنبيهات: {violations.length}{exam.maxViolations ? `/${exam.maxViolations}` : ""}</p></div><div className="flex items-center gap-2"><span aria-live="polite" className="rounded-lg bg-secondary px-3 py-2 font-semibold tabular-nums"><Clock3Icon className="me-1 inline size-4" />{time}</span>{exam.requiresFullscreen ? <Button variant="outline" size="sm" onClick={() => { startTransition(() => { void document.documentElement.requestFullscreen?.().then(() => setFullscreenRequested(true)).catch(() => undefined); }); }}><ExpandIcon data-icon="inline-start" />ملء الشاشة</Button> : null}<Button size="sm" onClick={() => setSubmitted(true)}>تسليم</Button></div></div></header>{violations.length ? <Alert><ShieldAlertIcon /><AlertTitle>تم تسجيل تنبيه داخل المحاولة</AlertTitle><AlertDescription>يمكنك المتابعة بهدوء. هذه التنبيهات لا تعني منع استخدام التطبيقات أو الأجهزة الأخرى.</AlertDescription></Alert> : null}<div className="grid gap-4">{exam.questions.map((question, index) => <Card key={question.id}><CardContent className="p-5"><p className="text-sm text-primary">السؤال {index + 1} · {question.maxScore} درجات</p><fieldset className="mt-3"><legend className="text-lg font-semibold">{question.text}</legend>{question.type === "SHORT_TEXT" ? <textarea aria-label={`إجابة السؤال ${index + 1}`} className="mt-4 min-h-28 w-full rounded-lg border bg-background p-3 text-sm" value={typeof answers[question.id] === "string" ? answers[question.id] as string : ""} onChange={(event) => setAnswers((value) => ({ ...value, [question.id]: event.target.value }))} /> : question.type === "TRUE_FALSE" ? <div className="mt-4 flex flex-wrap gap-3">{[[true, "صح"], [false, "خطأ"]].map(([value, label]) => <label key={String(value)} className="flex items-center gap-2 rounded-lg border p-3"><input type="radio" name={question.id} checked={answers[question.id] === value} onChange={() => setAnswers((all) => ({ ...all, [question.id]: value as boolean }))} />{label}</label>)}</div> : <div className="mt-4 grid gap-2">{question.options?.map((option) => { const selected = (answers[question.id] as string[] | undefined) ?? []; const multiple = question.type === "MULTIPLE_CHOICE"; return <label key={option.id} className="flex items-center gap-3 rounded-lg border p-3"><input type={multiple ? "checkbox" : "radio"} name={question.id} checked={selected.includes(option.id)} onChange={(event) => setAnswers((all) => ({ ...all, [question.id]: multiple ? (event.target.checked ? [...selected, option.id] : selected.filter((id) => id !== option.id)) : [option.id] }))} />{option.label}</label>; })}</div>}</fieldset></CardContent></Card>)}</div></div>;
}

export function UnifiedResultsPage({ results }: { results: UnifiedStudentResult[] }) { const [filter, setFilter] = useState<"ALL" | UnifiedStudentResult["type"]>("ALL"); const shown = useMemo(() => filter === "ALL" ? results : results.filter((result) => result.type === filter), [filter, results]); const labels = { ALL: "الكل", ONLINE_EXAM: "امتحانات المنصة", CENTER_SESSION_ASSESSMENT: "اختبارات الحصص", PAPER_EXAM: "امتحانات السنتر الورقية" }; return <div className="flex flex-col gap-5"><div><h1 className="text-2xl font-semibold">النتائج</h1><p className="mt-1 text-sm text-muted-foreground">نتائجك فقط، مع توضيح مصدر كل نتيجة.</p></div><div className="flex flex-wrap gap-2">{(Object.keys(labels) as Array<keyof typeof labels>).map((key) => <Button key={key} size="sm" variant={filter === key ? "default" : "outline"} onClick={() => setFilter(key)}>{labels[key]}</Button>)}</div><div className="grid gap-3">{shown.map((result) => <ResultCard key={result.id} result={result} />)}</div></div>; }
function ResultCard({ result }: { result: UnifiedStudentResult }) { const score = result.type === "CENTER_SESSION_ASSESSMENT" ? (result.attendance === "ABSENT" ? "غائب عن الحصة" : result.maxScore ? result.studentScore === undefined ? "لم تُرصد الدرجة بعد" : `${Math.min(result.studentScore, result.maxScore)} من ${result.maxScore}` : "لم يوجد اختبار في هذه الحصة") : result.type === "PAPER_EXAM" ? result.status === "ABSENT" ? "غائب" : result.studentScore === undefined ? "لم تُرصد الدرجة بعد" : `${result.studentScore} من ${result.maxScore}` : result.status === "HIDDEN" ? "النتيجة مخفية حتى النشر" : result.pendingManualReview ? "بانتظار مراجعة الإجابة النصية" : `${result.score} من ${result.maxScore}`; const source = result.type === "ONLINE_EXAM" ? "امتحان منصة" : result.type === "CENTER_SESSION_ASSESSMENT" ? "تقييم حصة سنتر" : "امتحان سنتر ورقي"; return <Card><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-primary">{source} · {result.subject}</p><h2 className="mt-1 font-semibold">{result.title}</h2><p className="mt-1 text-sm text-muted-foreground">{result.teacher} · {formatDate(result.date)}</p></div><div className="flex items-center gap-3"><p className="font-medium">{score}</p><Button size="sm" variant="outline" render={<Link href={`/results/${result.id}`} />} nativeButton={false}>التفاصيل</Button></div></CardContent></Card>; }
export function ResultDetailPage({ result }: { result: UnifiedStudentResult }) { return <div className="mx-auto max-w-3xl"><Link href="/results" className="text-sm font-medium text-primary hover:underline">العودة إلى النتائج</Link><Card className="mt-4"><CardHeader><p className="text-sm text-primary">{result.subject} · {formatDate(result.date)}</p><CardTitle className="mt-1 text-2xl">{result.title}</CardTitle></CardHeader><CardContent className="space-y-4"><ResultCard result={result} />{result.type === "ONLINE_EXAM" ? <Alert><ShieldAlertIcon /><AlertTitle>ملخص المحاولة</AlertTitle><AlertDescription>{result.violations ? `تم تسجيل ${result.violations} تنبيه داخل المحاولة.` : "لم يتم تسجيل تنبيهات في هذه المحاولة."}{result.pendingManualReview ? " توجد إجابة نصية بانتظار المراجعة." : ""}</AlertDescription></Alert> : result.type === "PAPER_EXAM" && result.note ? <Alert><FileTextIcon /><AlertTitle>ملاحظة ظاهرة للطالب</AlertTitle><AlertDescription>{result.note}</AlertDescription></Alert> : <p className="text-sm text-muted-foreground">يعرض هذا السجل معلومات نتيجتك فقط، دون ملاحظات الموظفين أو بيانات الطلاب الآخرين.</p>}</CardContent></Card></div>; }
