export type AccountStatus = "active" | "requires-review" | "inactive";
export type GuardianProfile = { id: string; fullName: string; relation: string; primaryPhone: string; secondaryPhone?: string; email?: string; preferredContactMethod: "phone" | "whatsapp" | "email"; receivesAttendanceNotifications: boolean; receivesResultNotifications: boolean; receivesPaymentNotifications: boolean; };
export type StudentProfile = { id: string; fullName: string; firstName: string; lastName: string; email?: string; phone: string; dateOfBirth?: string; gender?: "female" | "male"; grade: string; schoolName?: string; address?: string; centerName: string; primaryGroup: string; profileInitials: string; accountStatus: AccountStatus; joinedAt: string; activeSubjectsCount: number; guardian?: GuardianProfile; emergencyContact?: string; editableFields: string[]; readonlyFields: string[]; };
export type StudentAccountNotification = { id: string; title: string; message: string; createdAt: string; isRead: boolean; readAt?: string; relatedRoute?: string; actionLabel?: string; };
export type NotificationPreferences = { lessonUpdates: boolean; examReminders: boolean; resultUpdates: boolean; attendanceUpdates: boolean; subscriptionUpdates: boolean; paymentUpdates: boolean; announcements: boolean; guardianAttendanceMessages: boolean; guardianResultMessages: boolean; guardianPaymentMessages: boolean; };
export type UpdateStudentProfileInput = Pick<StudentProfile, "fullName" | "phone" | "email" | "schoolName" | "address">;
export type UpdateGuardianPreferencesInput = Partial<Pick<GuardianProfile, "preferredContactMethod" | "receivesAttendanceNotifications" | "receivesResultNotifications" | "receivesPaymentNotifications">>;
export type ChangePasswordInput = { currentPassword: string; newPassword: string };
export type MockAccountActionResult = { success: boolean; message: string };
export interface StudentProfileRepository { getProfile(): Promise<StudentProfile>; updateProfile(input: UpdateStudentProfileInput): Promise<StudentProfile>; updateGuardianPreferences(input: UpdateGuardianPreferencesInput): Promise<GuardianProfile>; changePassword(input: ChangePasswordInput): Promise<MockAccountActionResult>; }
export interface StudentNotificationsRepository { getNotifications(): Promise<StudentAccountNotification[]>; getUnreadCount(): Promise<number>; markAsRead(id: string): Promise<StudentAccountNotification | null>; markAllAsRead(): Promise<StudentAccountNotification[]>; getPreferences(): Promise<NotificationPreferences>; updatePreferences(input: NotificationPreferences): Promise<NotificationPreferences>; }
