export type AccountStatus = "active" | "requires_review" | "suspended" | "incomplete";
export type GuardianRelation = "father" | "mother" | "guardian" | "other";
export type ContactMethod = "whatsapp" | "phone" | "sms" | "email";
export type GuardianProfile = { id:string; fullName:string; relation:GuardianRelation; primaryPhone:string; secondaryPhone?:string; email?:string; preferredContactMethod:ContactMethod; receivesAttendanceNotifications:boolean; receivesResultNotifications:boolean; receivesPaymentNotifications:boolean; };
export type StudentProfile = { id:string; studentCode:string; fullName:string; firstName:string; lastName:string; email?:string; phone:string; dateOfBirth?:string; gender?:"female"|"male"; grade:string; schoolName?:string; address?:string; centerName:string; primaryGroup:string; profileInitials:string; accountStatus:AccountStatus; joinedAt:string; activeSubjectsCount:number; guardian?:GuardianProfile; emergencyContact?:string; editableFields:string[]; readonlyFields:string[]; };
export type UpdateStudentProfileInput = Pick<StudentProfile,"fullName"|"phone"|"email"|"schoolName"|"address">;
export type UpdateGuardianPreferencesInput = Pick<GuardianProfile,"preferredContactMethod"|"receivesAttendanceNotifications"|"receivesResultNotifications"|"receivesPaymentNotifications">;
export type ChangePasswordInput = {currentPassword:string;newPassword:string;}; export type MockAccountActionResult={success:boolean;message:string;};
export type NotificationType="lesson"|"exam"|"result"|"attendance"|"subscription"|"payment"|"announcement"|"system"; export type NotificationPriority="normal"|"important"|"urgent";
export type StudentAccountNotification={id:string;type:NotificationType;title:string;message:string;createdAt:string;readAt?:string;isRead:boolean;priority:NotificationPriority;relatedRoute?:string;actionLabel?:string;courseId?:string;lessonId?:string;examId?:string;paymentId?:string;};
export type NotificationPreferences={lessonUpdates:boolean;examReminders:boolean;resultUpdates:boolean;attendanceUpdates:boolean;subscriptionUpdates:boolean;paymentUpdates:boolean;announcements:boolean;guardianAttendanceMessages:boolean;guardianResultMessages:boolean;guardianPaymentMessages:boolean;};
export interface StudentProfileRepository {getProfile():Promise<StudentProfile>;updateProfile(input:UpdateStudentProfileInput):Promise<StudentProfile>;updateGuardianPreferences(input:UpdateGuardianPreferencesInput):Promise<GuardianProfile>;changePassword(input:ChangePasswordInput):Promise<MockAccountActionResult>;}
export interface StudentNotificationsRepository {getNotifications():Promise<StudentAccountNotification[]>;getUnreadCount():Promise<number>;markAsRead(id:string):Promise<StudentAccountNotification|null>;markAllAsRead():Promise<StudentAccountNotification[]>;getPreferences():Promise<NotificationPreferences>;updatePreferences(input:NotificationPreferences):Promise<NotificationPreferences>;}
