import Image from "next/image";
import Link from "next/link";

import { buttonVariants } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import type { CatalogCourse, CatalogTeacher, StoreProduct } from "@/features/public-catalog/types/catalog";

export function TeachersGallery({ teachers, courses }: { teachers: CatalogTeacher[]; courses: CatalogCourse[] }) {
  return <main className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 sm:py-10 lg:px-8"><p className="text-xs font-semibold text-primary">فريق قلاّج</p><h1 className="mt-1 text-3xl font-bold">المدرسون</h1><p className="mt-2 text-sm text-muted-foreground">المدرسون الذين لديهم كورسات منشورة حاليًا.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{teachers.map((teacher) => <Link key={teacher.id} href={`/teachers/${teacher.id}`} className="group rounded-xl focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50 active:scale-[.99]"><Card className="h-full transition-all group-hover:-translate-y-0.5 group-hover:ring-primary/35 group-hover:shadow-md"><CardContent className="flex gap-4"><div className="relative size-24 shrink-0 overflow-hidden rounded-xl bg-primary/10">{teacher.photoUrl ? <Image src={teacher.photoUrl} alt={teacher.name} fill sizes="96px" className="object-cover" unoptimized /> : <span className="flex h-full items-center justify-center text-2xl font-bold text-primary">{teacher.initials}</span>}</div><div className="min-w-0"><h2 className="text-lg font-bold">{teacher.name}</h2><p className="text-sm font-medium text-primary">{teacher.subject}</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{teacher.intro}</p><p className="mt-2 text-xs text-muted-foreground">{courses.filter((course) => course.teacherId === teacher.id).length} كورسات منشورة</p></div></CardContent></Card></Link>)}</div></main>;
}

export function TeacherProfilePage({ teacher, courses, products }: { teacher: CatalogTeacher; courses: CatalogCourse[]; products: StoreProduct[] }) {
  return <main className="mx-auto w-full max-w-7xl px-4 py-6 sm:px-6 sm:py-10 lg:px-8"><section className="flex flex-col gap-4 rounded-xl border bg-card p-4 sm:flex-row sm:items-center sm:p-6"><div className="relative size-28 shrink-0 overflow-hidden rounded-xl bg-primary/10 sm:size-36">{teacher.photoUrl ? <Image src={teacher.photoUrl} alt={teacher.name} fill sizes="144px" className="object-cover" unoptimized /> : <span className="flex h-full items-center justify-center text-3xl font-bold text-primary">{teacher.initials}</span>}</div><div><p className="text-sm font-semibold text-primary">{teacher.subject}</p><h1 className="mt-1 text-3xl font-bold">{teacher.name}</h1><p className="mt-3 max-w-2xl leading-7 text-muted-foreground">{teacher.intro}</p><p className="mt-2 text-sm text-muted-foreground">{teacher.grades.join(" · ")}</p></div></section><section className="mt-8"><h2 className="text-2xl font-bold">كورسات المدرس</h2><div className="mt-4 grid grid-cols-2 gap-3 lg:grid-cols-3">{courses.map((course) => <Link key={course.id} href={`/courses/${course.id}`} className="overflow-hidden rounded-xl border bg-card transition hover:border-primary/40 hover:shadow-md focus-visible:outline-none focus-visible:ring-3 focus-visible:ring-ring/50 active:scale-[.99]"><div className="relative aspect-video bg-secondary"><Image src={course.cover} alt={course.coverAlt} fill sizes="(max-width:640px) 50vw, 33vw" className="object-cover" unoptimized /></div><div className="p-3"><h3 className="line-clamp-2 font-semibold">{course.title}</h3><p className="mt-1 text-xs text-muted-foreground">{course.grade}</p></div></Link>)}</div></section>{products.length ? <section className="mt-8"><h2 className="text-2xl font-bold">من المتجر</h2><div className="mt-4 flex flex-wrap gap-2">{products.map((product) => <Link key={product.id} href={`/store/${product.id}`} className={buttonVariants({ variant: "outline" })}>{product.title}</Link>)}</div></section> : null}</main>;
}
