"use client";
import Link from "next/link";
import { useState } from "react";
import { BellIcon } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { StudentAccountNotification, StudentProfile } from "../types/account";
import { updateStudentProfile } from "../services/account-client";

export function ProfilePage({ initial: profile }: { initial: StudentProfile }) { const [phone, setPhone] = useState(profile.phone); const [guardianName, setGuardianName] = useState(profile.guardian?.fullName ?? ""); const [guardianPhone, setGuardianPhone] = useState(profile.guardian?.primaryPhone ?? ""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const save = async () => { setSaving(true); setMessage(""); try { await updateStudentProfile({ phone: phone || null, guardianName: guardianName || null, guardianPhone: guardianPhone || null }); setMessage("تم حفظ بيانات الاتصال."); } catch { setMessage("تعذر حفظ البيانات الآن."); } finally { setSaving(false); } }; return <div className="space-y-5"><Card><CardContent><h1 className="text-2xl font-semibold">{profile.fullName}</h1><p className="mt-1 text-sm text-muted-foreground">{profile.grade}</p></CardContent></Card><Card><CardHeader><CardTitle>البيانات الشخصية</CardTitle></CardHeader><CardContent className="space-y-3"><label className="block text-sm font-medium">الاسم<Input disabled value={profile.fullName} /></label><label className="block text-sm font-medium">الهاتف<Input value={phone} onChange={(event) => setPhone(event.target.value)} /></label><label className="block text-sm font-medium">البريد<Input disabled value={profile.email ?? "غير مسجل"} /></label><p className="rounded-lg bg-secondary/50 p-3 text-sm">البريد والصف والمدرسة والعنوان لا تُحفظ عبر الخادم من هذه الصفحة.</p></CardContent></Card><Card><CardHeader><CardTitle>ولي الأمر</CardTitle></CardHeader><CardContent className="space-y-3"><label className="block text-sm font-medium">الاسم<Input value={guardianName} onChange={(event) => setGuardianName(event.target.value)} /></label><label className="block text-sm font-medium">الهاتف<Input value={guardianPhone} onChange={(event) => setGuardianPhone(event.target.value)} /></label><Button disabled={saving} onClick={save}>{saving ? "جارٍ الحفظ…" : "حفظ بيانات الاتصال"}</Button>{message ? <p role="status" className="text-sm text-muted-foreground">{message}</p> : null}</CardContent></Card></div>; }
export function NotificationsPage({ initial }: { initial: StudentAccountNotification[] }) { const [query, setQuery] = useState(""); const visible = initial.filter((item) => `${item.title} ${item.message}`.includes(query)); return <div className="space-y-4"><div><h1 className="text-3xl font-semibold">الإشعارات</h1><p className="text-sm text-muted-foreground">{initial.filter((item) => !item.isRead).length} غير مقروءة. حالة القراءة مؤقتة في هذه المرحلة.</p></div><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="البحث في الإشعارات" />{visible.map((item) => <Card key={item.id}><CardContent className="flex gap-3"><BellIcon className="text-primary" /><div className="min-w-0 flex-1"><strong>{item.title}</strong><p className="text-sm text-muted-foreground">{item.message}</p><span className="text-xs text-muted-foreground">{item.isRead ? "مقروء" : "غير مقروء"}</span></div>{item.relatedRoute ? <Button size="sm" render={<Link href={item.relatedRoute} />} nativeButton={false}>{item.actionLabel ?? "عرض"}</Button> : null}</CardContent></Card>)}</div>; }
