import { MockStudentSubscriptionsRepository } from "@/mocks/repositories/mock-student-subscriptions-repository";
import type { ActivationCodeResult, CreatePaymentRequestInput, PaymentRequest, StudentSubscription, StudentSubscriptionsRepository, SubscriptionOffer } from "../types/subscriptions";
const repository = new MockStudentSubscriptionsRepository();
export const getStudentSubscriptions = (repo: StudentSubscriptionsRepository = repository): Promise<StudentSubscription[]> => repo.getSubscriptions();
export const getAvailableSubscriptionOffers = (repo: StudentSubscriptionsRepository = repository): Promise<SubscriptionOffer[]> => repo.getSubscriptionOffers();
export const getStudentSubscriptionById = (id: string, repo: StudentSubscriptionsRepository = repository): Promise<StudentSubscription | null> => repo.getSubscriptionById(id);
export const validateStudentActivationCode = (code: string, repo: StudentSubscriptionsRepository = repository): Promise<ActivationCodeResult> => repo.validateActivationCode(code);
export const mockActivateStudentSubscription = (code: string, repo: StudentSubscriptionsRepository = repository): Promise<ActivationCodeResult> => repo.activateWithCode(code);
export const getStudentPayments = (repo: StudentSubscriptionsRepository = repository): Promise<PaymentRequest[]> => repo.getPayments();
export const getStudentPaymentById = (id: string, repo: StudentSubscriptionsRepository = repository): Promise<PaymentRequest | null> => repo.getPaymentById(id);
export const createMockPaymentRequest = (input: CreatePaymentRequestInput, repo: StudentSubscriptionsRepository = repository): Promise<PaymentRequest> => repo.createPaymentRequest(input);
